### ISSUE TITLE
cross_validation is deprecated in new sklearn version

### ISSUE THREAD

**Issue by aaronkl** [automl/HPOlib1.5#46]
Could we just replace that and set in the requirements sklearn >= 0.18

**Comment by KEggensperger** [comment]
Where is it used?

**Comment by aaronkl** [comment]
in the openml data manager

**Comment by KEggensperger** [comment]
True. I am not aware of anything that requires a lower scikit-learn version --> Yes, we could replace it.

**Comment by mfeurer** [comment]
Fixed by  4cc8309.
