### ISSUE TITLE
Cloning the repo downloads 500Mb+

### ISSUE THREAD

**Issue by sfalkner** [automl/HPOlib1.5#52]
Somehow, we should reduce the size of the repo to make it faster to install (or we should put in on PyPi).
The main problem are the surrogates that are relatively large. I don't know if deleting the surrogate branch will solve the problem, but before that we need to refactor the surrogate benchmarks such that they download the surrogates from an external source.

**Comment by KEggensperger** [comment]
I fully agree! As far as I understood you are currently refactoring the surrogate branch, so I am very happy to delete the old one once this is done.

**Comment by KEggensperger** [comment]
Should be resolved by now.
