### ISSUE TITLE
Remove code duplication in svm_on_mnist and fully_connected_network_on_mnist

### ISSUE THREAD

**Issue by KEggensperger** [automl/HPOlib1.5#6]
We could have base class for MNIST-benchmarks, or a module for frequently used helper functions, such as downloading datasets. What do you think?

**Comment by sfalkner** [comment]
Or we have an additional submodule for datasets. That would probably help with a centralized config/data folder. Then, every benchmark can just instantiate the dataset class which handles the downloading/reading from disc.
