### ISSUE TITLE
error of running example

### ISSUE THREAD

**Issue by qqliang** [automl/HPOlib1.5#63]
I got an error when I run example. error as follow:
Exception: Compilation failed (return status=1): /usr/bin/ld: /usr/local/Python3.4.4/lib/libpython3.4m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC. /usr/local/Python3.4.4/lib/libpython3.4m.a: error adding symbols: 错误的值. collect2: 错误：ld 返回 1. 

how can I solve it?

**Comment by qqliang** [comment]
the example is "smac_on_LogisticRegression10CVOnMinist"

**Comment by KEggensperger** [comment]
Hi, unfortunately, I can't see from the error message where exactly the error happens. Do the other examples run? 
If yes, then this is most likely due to LogisticRegression using lasagne/theano or maybe that the SMAC interface has changed in the meantime.

**Comment by qqliang** [comment]
yeah, I check this error, I found that generated by theano. I can install theano correctly, but when I run example, I will get this error

**Comment by KEggensperger** [comment]
Which theano version are you using? I think this example requires the following:
```
# We need lasagne 0.2dev1 + corresponding theano version
theano==0.8.2
git+https://github.com/Lasagne/Lasagne.git@master
```

**Comment by qqliang** [comment]
yes, I have checked the version of requirement, but the problem still exist. I guess the reason is "--enable-share" must be set during install python?

**Comment by qqliang** [comment]
another question: 
I found hp-nnet and hp-dbnet benchmarks description in here: https://hpolib.readthedocs.io/en/development/algorithms_and_datasets.html#benchmarks-overview. But I didn't found in HPOlib2, is remove it? why? where I can get it ?

**Comment by KEggensperger** [comment]
Yes, these are old benchmarks which we had in an old version of HPOlib and no longer maintain in HPOlib2 based on Python3.

**Comment by KEggensperger** [comment]
About the error: Did setting this flag help?

**Comment by qqliang** [comment]
No, I haven't set it.

**Comment by qqliang** [comment]
I reinstall python with "./configure --prefix=/usr/local/python3.4.4 --enable-shared CFLAGS=-fPIC", the Theano works.

**Comment by KEggensperger** [comment]
Thank you very much. That is interesting and good to know!

**Comment by qqliang** [comment]
Where I can get the hp-nnet and hp-dbnet benchmarks, I want to use SMAC3 to optimize its space. Thanks!

**Comment by KEggensperger** [comment]
The code to start the benchmark and its search space can be found here https://github.com/automl/HPOlib-hpnnet and the neural network code is here https://github.com/hyperopt/hyperopt-nnet/tree/master/hpnnet. However, unfortunately we cannot provide any further support for these.
