### ISSUE TITLE
Surrogate branch

### ISSUE THREAD

**Issue by bkj** [automl/HPOlib1.5#67]
The [HpBandSter icml_2018 branch](https://github.com/automl/HpBandSter/tree/icml_2018) repo requires the HPOLib2 surrogate branch to reproduce some experimental results.  It seems like the surrogate branch has been deleted (per issue https://github.com/automl/HPOlib2/issues/52) -- is there somewhere that I can download it from?

~ Ben

**Comment by KEggensperger** [comment]
Yes, the surrogate branch has been deleted after merging into development. So you should find everything in the current development branch?
