### ISSUE TITLE
Unable to load dependencies for BNN examples

### ISSUE THREAD

**Issue by Neeratyoy** [automl/HPOlib1.5#77]
Hi,

I am trying to work on this [example](https://github.com/automl/HpBandSter/blob/icml_2018/icml_2018_experiments/experiments/workers/bnn.py) where BostonHousing is loaded using,
`from hpolib.benchmarks.ml.bnn_benchmark import BNNOnBostonHousing`

However, this[ imports BayesianNeuralNetwork from the _sgmcmc_ package](https://github.com/automl/HPOlib2/blob/development/hpolib/benchmarks/ml/bnn_benchmark.py#L13).
The [_sgmcmc_ package](https://github.com/stokasto/sgmcmc/blob/master/sgmcmc/bnn/model.py) seems to have just one branch with no class definition for BayesianNeuralNetwork.

As a result, `from hpolib.benchmarks.ml.bnn_benchmark import BNNOnBostonHousing` gives the error,
`ImportError: cannot import name 'BayesianNeuralNetwork'`

Am I missing something here? How can I solve this?

Thanks.

**Comment by KEggensperger** [comment]
Hi, Yes, the package you referenced does not have the BNN interface you need. You need to use a different fork from here
`pip install git+https://github.com/automl/sgmcmc.git`

**Comment by Neeratyoy** [comment]
Thanks a lot! 
That worked!
