### ISSUE TITLE
Configuration space not always known at time of constructing a benchmark

### ISSUE THREAD

**Issue by mfeurer** [automl/HPOlib1.5#9]
When creating a benchmark for auto-sklearn, the configuration space of auto-sklearn depends on the data one is working with. The method `get_configuration_space` of the current benchmarks does not provide a way to access the current dataset. Therefore, I propose to change the method `get_configuration_space` from an `@staticmethod` to a `@classmethod`. This at least allows to call other static methods or class methods.

**Comment by mfeurer** [comment]
@sfalkner @aaronkl could you please comment on this proposal?

**Comment by sfalkner** [comment]
I would try to keep things as simple as possible, @mfeurer. How about a different benchmark for the different cases (I guess regression, classification and then certain special cases...)? Then the config space would be know at all times. A `@classmethod` wouldn't really change anything as you don't have an object which could tell you about the data.

**Comment by mfeurer** [comment]
It's mostly certain cases of classification. This basically changes the complexity to be in the benchmark. I'll do that since it seems to keep the overall complexity low.
